joylink:
  device: "/dev/input/js0"
  device_name: ""

  deadzone: 0.05
  sticky_buttons: false
  publish_rate: 100.0
  coalesce_interval: 0.001
  frame_id: "joy"

  publisher_type: "zmq"

  ros2:
    topic: "joy"

  zmq:
    address: "tcp://*:5555"

  debug_raw: true

  button_mapping:
    a: 0
    b: 1
    x: 3
    y: 4
    lb: 6
    rb: 7
    left_stick: 13
    right_stick: 14
    touchpad: -1
    start: -1
    back: -1
    guide: -1
    f1: 10
    f2: 11

  axes_mapping:
    left_stick_x: 1
    left_stick_y: 0
    right_stick_x: 3
    right_stick_y: 2
    lt: 5
    rt: 4
    dpad_x: 7
    dpad_y: 6

  axis_reverse: [0, 1, 2, 3, 6, 7]
